baseURL = 'https://docs.firestartr.dev/docs/'
languageCode = 'en-us'
title = 'Firestartr Documentation'
theme = 'hugo-book'
disablePathToLower = true

[params]
  BookComments = false
  BookSection = '*'
  BookPortableLinks = true

[markup]
  [markup.goldmark]
    [markup.goldmark.renderHooks]
      [markup.goldmark.renderHooks.link]
        useEmbedded = 'auto'
      [markup.goldmark.renderHooks.image]
        useEmbedded = 'auto'
